#!/usr/bin/env python3
"""
Comprehensive FID and IS calculation script for 3M dataset analysis.

This script performs:
1. FID calculations between folder combinations (set1, set2, set3)
2. Class-wise FID calculations for conditional datasets
3. Inception Score calculations for all specified folders
4. Results saved to Excel files in the results folder

Author: Generated by AI Assistant
Date: September 17, 2025
"""

import os
import sys
import glob
import pandas as pd
import numpy as np
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms, models
from scipy.linalg import sqrtm
from collections import defaultdict
import argparse
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# Ensure we're using the virtual environment
def activate_venv():
    """Activate the virtual environment if not already activated"""
    venv_path = "/home/sanyam/playground/new_env"
    if venv_path not in sys.path:
        sys.path.insert(0, os.path.join(venv_path, "lib", "python3.8", "site-packages"))
    
    # Set environment variables
    os.environ['VIRTUAL_ENV'] = venv_path
    os.environ['PATH'] = f"{os.path.join(venv_path, 'bin')}:{os.environ.get('PATH', '')}"

class InceptionV3Features(nn.Module):
    """Inception v3 model for feature extraction using the pool3 layer (2048 features)"""
    
    def __init__(self):
        super().__init__()
        
        # Load pretrained InceptionV3
        inception = models.inception_v3(pretrained=True, transform_input=False)
        inception.eval()
        
        # Get features up to the pool3 layer (before classification)
        self.blocks = nn.ModuleList([
            inception.Conv2d_1a_3x3,
            inception.Conv2d_2a_3x3, 
            inception.Conv2d_2b_3x3,
            nn.MaxPool2d(kernel_size=3, stride=2),
            inception.Conv2d_3b_1x1,
            inception.Conv2d_4a_3x3,
            nn.MaxPool2d(kernel_size=3, stride=2),
            inception.Mixed_5b,
            inception.Mixed_5c,
            inception.Mixed_5d,
            inception.Mixed_6a,
            inception.Mixed_6b,
            inception.Mixed_6c,
            inception.Mixed_6d,
            inception.Mixed_6e,
            inception.Mixed_7a,
            inception.Mixed_7b,
            inception.Mixed_7c,
            nn.AdaptiveAvgPool2d(output_size=(1, 1))
        ])
        
        for param in self.parameters():
            param.requires_grad = False
            
        self.eval()
    
    def forward(self, x):
        # Resize to 299x299 if needed
        if x.shape[2:] != (299, 299):
            x = F.interpolate(x, size=(299, 299), mode='bilinear', align_corners=False)
        
        # Normalize input to [-1, 1] range
        x = (x - 0.5) * 2
        
        # Forward through all blocks
        for block in self.blocks:
            x = block(x)
        
        # Flatten
        return x.view(x.size(0), -1)

class FIDCalculator:
    """Calculate Frechet Inception Distance between two sets of images"""
    
    def __init__(self, device='cuda' if torch.cuda.is_available() else 'cpu'):
        self.device = device
        self.inception_model = InceptionV3Features().to(device)
        self.transform = transforms.Compose([
            transforms.Resize((299, 299)),
            transforms.ToTensor(),
        ])
    
    def get_features(self, images_path, batch_size=32):
        """Extract features from images in a directory"""
        image_files = []
        for ext in ['*.png', '*.jpg', '*.jpeg']:
            image_files.extend(glob.glob(os.path.join(images_path, ext)))
        
        if not image_files:
            raise ValueError(f"No images found in {images_path}")
        
        features = []
        
        for i in range(0, len(image_files), batch_size):
            batch_files = image_files[i:i+batch_size]
            batch_images = []
            
            for img_path in batch_files:
                try:
                    img = Image.open(img_path).convert('RGB')
                    img_tensor = self.transform(img)
                    batch_images.append(img_tensor)
                except Exception as e:
                    print(f"Error loading {img_path}: {e}")
                    continue
            
            if batch_images:
                batch_tensor = torch.stack(batch_images).to(self.device)
                with torch.no_grad():
                    batch_features = self.inception_model(batch_tensor)
                features.append(batch_features.cpu().numpy())
        
        if not features:
            raise ValueError(f"No valid images found in {images_path}")
        
        return np.concatenate(features, axis=0)
    
    def calculate_fid(self, features1, features2):
        """Calculate FID between two sets of features"""
        mu1, sigma1 = np.mean(features1, axis=0), np.cov(features1, rowvar=False)
        mu2, sigma2 = np.mean(features2, axis=0), np.cov(features2, rowvar=False)
        
        diff = mu1 - mu2
        
        # Calculate sqrt((sigma1 @ sigma2))
        covmean, _ = sqrtm(sigma1.dot(sigma2), disp=False)
        if np.iscomplexobj(covmean):
            covmean = covmean.real
        
        fid = diff.dot(diff) + np.trace(sigma1) + np.trace(sigma2) - 2 * np.trace(covmean)
        return fid
    
    def calculate_fid_between_paths(self, path1, path2):
        """Calculate FID between two image directories"""
        print(f"Calculating FID between {path1} and {path2}")
        features1 = self.get_features(path1)
        features2 = self.get_features(path2)
        return self.calculate_fid(features1, features2)

class ISCalculator:
    """Calculate Inception Score for a set of images"""
    
    def __init__(self, device='cuda' if torch.cuda.is_available() else 'cpu'):
        self.device = device
        # Load full InceptionV3 model for classification
        self.inception_model = models.inception_v3(pretrained=True).to(device)
        self.inception_model.eval()
        
        self.transform = transforms.Compose([
            transforms.Resize((299, 299)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ])
    
    def get_predictions(self, images_path, batch_size=32):
        """Get predictions from InceptionV3 for images in a directory"""
        image_files = []
        for ext in ['*.png', '*.jpg', '*.jpeg']:
            image_files.extend(glob.glob(os.path.join(images_path, ext)))
        
        if not image_files:
            raise ValueError(f"No images found in {images_path}")
        
        predictions = []
        
        for i in range(0, len(image_files), batch_size):
            batch_files = image_files[i:i+batch_size]
            batch_images = []
            
            for img_path in batch_files:
                try:
                    img = Image.open(img_path).convert('RGB')
                    img_tensor = self.transform(img)
                    batch_images.append(img_tensor)
                except Exception as e:
                    print(f"Error loading {img_path}: {e}")
                    continue
            
            if batch_images:
                batch_tensor = torch.stack(batch_images).to(self.device)
                with torch.no_grad():
                    batch_pred = self.inception_model(batch_tensor)
                    batch_pred = F.softmax(batch_pred, dim=1)
                predictions.append(batch_pred.cpu().numpy())
        
        if not predictions:
            raise ValueError(f"No valid images found in {images_path}")
        
        return np.concatenate(predictions, axis=0)
    
    def calculate_inception_score(self, images_path, splits=10):
        """Calculate Inception Score for images in a directory"""
        print(f"Calculating IS for {images_path}")
        predictions = self.get_predictions(images_path)
        
        # Split predictions into chunks
        split_size = predictions.shape[0] // splits
        scores = []
        
        for i in range(splits):
            start_idx = i * split_size
            end_idx = (i + 1) * split_size if i < splits - 1 else predictions.shape[0]
            
            preds = predictions[start_idx:end_idx]
            
            # Calculate p(y|x) for each sample
            py_given_x = preds
            
            # Calculate p(y) = E[p(y|x)]
            py = np.mean(py_given_x, axis=0)
            
            # Calculate KL divergence
            kl_div = py_given_x * (np.log(py_given_x + 1e-10) - np.log(py + 1e-10))
            kl_div = np.sum(kl_div, axis=1)
            
            # Calculate IS for this split
            is_score = np.exp(np.mean(kl_div))
            scores.append(is_score)
        
        return np.mean(scores), np.std(scores)

class ClassLabelExtractor:
    """Extract class labels from filenames based on folder conventions"""
    
    @staticmethod
    def extract_class_label(filename, folder_type):
        """
        Extract class label based on folder type and filename pattern
        
        Args:
            filename: Image filename
            folder_type: Type of folder ('cdiff', 'cgan', 'training-c')
        
        Returns:
            Class label as string
        """
        if folder_type in ['cdiff', 'cgan']:
            # Format: {class}_{something}_{something}.png
            return filename.split('_')[0]
        elif folder_type == 'training-c':
            # Format: class_{class}_{something}.png
            parts = filename.split('_')
            if len(parts) >= 2 and parts[0] == 'class':
                return parts[1]
            else:
                # Fallback: try to extract from different position
                return parts[-1].split('.')[0]
        else:
            return None
    
    @staticmethod
    def get_class_images(folder_path, folder_type):
        """
        Group images by class label
        
        Returns:
            Dictionary mapping class labels to list of image paths
        """
        class_images = defaultdict(list)
        
        image_files = []
        for ext in ['*.png', '*.jpg', '*.jpeg']:
            image_files.extend(glob.glob(os.path.join(folder_path, ext)))
        
        for img_path in image_files:
            filename = os.path.basename(img_path)
            class_label = ClassLabelExtractor.extract_class_label(filename, folder_type)
            
            if class_label is not None:
                class_images[class_label].append(img_path)
        
        return dict(class_images)

class FIDISAnalyzer:
    """Main analyzer class that orchestrates all calculations"""
    
    def __init__(self, base_dir):
        self.base_dir = Path(base_dir)
        self.results_dir = self.base_dir / "results"
        self.results_dir.mkdir(exist_ok=True)
        
        # Initialize calculators
        self.fid_calc = FIDCalculator()
        self.is_calc = ISCalculator()
        
        # Define folder mappings
        self.folder_mappings = {
            'cdiff': '3m-cDiff-128',
            'cgan': '3m-cGAN-128',
            'training-c': '3m-training-c-128',
            'diff': '3m-Diff-128',
            'gan': '3m-GAN-128',
            'training': '3m-training-128'
        }
        
        # Results storage
        self.fid_results = []
        self.is_results = []
    
    def create_class_subdirs(self, source_folder, folder_type, target_base):
        """Create class-wise subdirectories from a conditional folder"""
        source_path = self.base_dir / self.folder_mappings[source_folder]
        class_images = ClassLabelExtractor.get_class_images(str(source_path), folder_type)
        
        created_dirs = []
        
        for class_label, image_paths in class_images.items():
            class_dir = self.base_dir / f"{target_base}-class-{class_label}"
            class_dir.mkdir(exist_ok=True)
            
            # Copy or create symlinks to images
            for img_path in image_paths:
                img_name = os.path.basename(img_path)
                target_path = class_dir / img_name
                
                if not target_path.exists():
                    # Create symlink to save space
                    try:
                        os.symlink(img_path, str(target_path))
                    except:
                        # Fallback to copying if symlink fails
                        import shutil
                        shutil.copy2(img_path, str(target_path))
            
            created_dirs.append(str(class_dir))
        
        return created_dirs
    
    def calculate_set1_fid(self):
        """Calculate FID for set1: (cdiff, cgan, training-c)"""
        print("\n=== Calculating Set1 FID (cdiff, cgan, training-c) ===")
        
        folders = ['cdiff', 'cgan', 'training-c']
        folder_paths = [str(self.base_dir / self.folder_mappings[f]) for f in folders]
        
        for i in range(len(folders)):
            for j in range(i+1, len(folders)):
                fid_score = self.fid_calc.calculate_fid_between_paths(folder_paths[i], folder_paths[j])
                
                self.fid_results.append({
                    'Set': 'Set1',
                    'Folder1': folders[i],
                    'Folder2': folders[j],
                    'FID': fid_score,
                    'Type': 'Overall'
                })
                
                print(f"FID between {folders[i]} and {folders[j]}: {fid_score:.4f}")
    
    def calculate_set2_fid(self):
        """Calculate class-wise FID for set2: (cdiff classwise, cgan classwise, training-c classwise)"""
        print("\n=== Calculating Set2 FID (Class-wise) ===")
        
        # Create class-wise subdirectories
        cdiff_class_dirs = self.create_class_subdirs('cdiff', 'cdiff', '3m-cDiff-128')
        cgan_class_dirs = self.create_class_subdirs('cgan', 'cgan', '3m-cGAN-128')
        training_class_dirs = self.create_class_subdirs('training-c', 'training-c', '3m-training-c-128')
        
        all_class_dirs = {
            'cdiff': cdiff_class_dirs,
            'cgan': cgan_class_dirs,
            'training-c': training_class_dirs
        }
        
        # Find common classes
        all_classes = set()
        for dirs in all_class_dirs.values():
            for dir_path in dirs:
                class_label = os.path.basename(dir_path).split('-class-')[-1]
                all_classes.add(class_label)
        
        # Calculate FID for each class between folder pairs
        folder_pairs = [('cdiff', 'cgan'), ('cdiff', 'training-c'), ('cgan', 'training-c')]
        
        for class_label in sorted(all_classes):
            print(f"\nProcessing class {class_label}:")
            
            for folder1, folder2 in folder_pairs:
                dir1 = None
                dir2 = None
                
                # Find directories for this class
                for dir_path in all_class_dirs[folder1]:
                    if dir_path.endswith(f'-class-{class_label}'):
                        dir1 = dir_path
                        break
                
                for dir_path in all_class_dirs[folder2]:
                    if dir_path.endswith(f'-class-{class_label}'):
                        dir2 = dir_path
                        break
                
                if dir1 and dir2 and os.path.exists(dir1) and os.path.exists(dir2):
                    try:
                        fid_score = self.fid_calc.calculate_fid_between_paths(dir1, dir2)
                        
                        self.fid_results.append({
                            'Set': 'Set2',
                            'Folder1': f"{folder1}-class-{class_label}",
                            'Folder2': f"{folder2}-class-{class_label}",
                            'FID': fid_score,
                            'Type': f'Class-{class_label}'
                        })
                        
                        print(f"  FID between {folder1}-class-{class_label} and {folder2}-class-{class_label}: {fid_score:.4f}")
                    except Exception as e:
                        print(f"  Error calculating FID for class {class_label} between {folder1} and {folder2}: {e}")
    
    def calculate_set3_fid(self):
        """Calculate FID for set3: (diff, gan, training)"""
        print("\n=== Calculating Set3 FID (diff, gan, training) ===")
        
        folders = ['diff', 'gan', 'training']
        folder_paths = [str(self.base_dir / self.folder_mappings[f]) for f in folders]
        
        for i in range(len(folders)):
            for j in range(i+1, len(folders)):
                fid_score = self.fid_calc.calculate_fid_between_paths(folder_paths[i], folder_paths[j])
                
                self.fid_results.append({
                    'Set': 'Set3',
                    'Folder1': folders[i],
                    'Folder2': folders[j],
                    'FID': fid_score,
                    'Type': 'Overall'
                })
                
                print(f"FID between {folders[i]} and {folders[j]}: {fid_score:.4f}")
    
    def calculate_inception_scores(self):
        """Calculate Inception Scores for all specified folders"""
        print("\n=== Calculating Inception Scores ===")
        
        # Overall folders
        overall_folders = ['cdiff', 'cgan', 'diff', 'gan', 'training', 'training-c']
        
        for folder in overall_folders:
            folder_path = str(self.base_dir / self.folder_mappings[folder])
            if os.path.exists(folder_path):
                try:
                    is_mean, is_std = self.is_calc.calculate_inception_score(folder_path)
                    
                    self.is_results.append({
                        'Folder': folder,
                        'IS_Mean': is_mean,
                        'IS_Std': is_std,
                        'Type': 'Overall'
                    })
                    
                    print(f"IS for {folder}: {is_mean:.4f} ± {is_std:.4f}")
                except Exception as e:
                    print(f"Error calculating IS for {folder}: {e}")
        
        # Class-wise IS for conditional folders
        conditional_folders = ['cdiff', 'cgan', 'training-c']
        
        for folder in conditional_folders:
            folder_type = folder if folder != 'training-c' else 'training-c'
            source_path = self.base_dir / self.folder_mappings[folder]
            class_images = ClassLabelExtractor.get_class_images(str(source_path), folder_type)
            
            for class_label in sorted(class_images.keys()):
                class_dir = self.base_dir / f"{self.folder_mappings[folder]}-class-{class_label}"
                
                if class_dir.exists():
                    try:
                        is_mean, is_std = self.is_calc.calculate_inception_score(str(class_dir))
                        
                        self.is_results.append({
                            'Folder': f"{folder}-class-{class_label}",
                            'IS_Mean': is_mean,
                            'IS_Std': is_std,
                            'Type': f'Class-{class_label}'
                        })
                        
                        print(f"IS for {folder}-class-{class_label}: {is_mean:.4f} ± {is_std:.4f}")
                    except Exception as e:
                        print(f"Error calculating IS for {folder}-class-{class_label}: {e}")
    
    def save_results(self):
        """Save all results to Excel files"""
        print("\n=== Saving Results ===")
        
        # Save FID results
        if self.fid_results:
            fid_df = pd.DataFrame(self.fid_results)
            fid_output_path = self.results_dir / "FID_Results.xlsx"
            fid_df.to_excel(str(fid_output_path), index=False)
            print(f"FID results saved to {fid_output_path}")
        
        # Save IS results
        if self.is_results:
            is_df = pd.DataFrame(self.is_results)
            is_output_path = self.results_dir / "IS_Results.xlsx"
            is_df.to_excel(str(is_output_path), index=False)
            print(f"IS results saved to {is_output_path}")
        
        # Save combined results
        if self.fid_results and self.is_results:
            with pd.ExcelWriter(str(self.results_dir / "Combined_Results.xlsx")) as writer:
                fid_df.to_excel(writer, sheet_name='FID_Results', index=False)
                is_df.to_excel(writer, sheet_name='IS_Results', index=False)
            print(f"Combined results saved to {self.results_dir / 'Combined_Results.xlsx'}")
    
    def run_analysis(self):
        """Run complete FID and IS analysis"""
        print("Starting FID and IS Analysis...")
        print(f"Base directory: {self.base_dir}")
        print(f"Results will be saved to: {self.results_dir}")
        
        try:
            # FID Calculations
            self.calculate_set1_fid()
            self.calculate_set2_fid()
            self.calculate_set3_fid()
            
            # IS Calculations
            self.calculate_inception_scores()
            
            # Save results
            self.save_results()
            
            print("\n=== Analysis Complete ===")
            print(f"Total FID calculations: {len(self.fid_results)}")
            print(f"Total IS calculations: {len(self.is_results)}")
            
        except Exception as e:
            print(f"Error during analysis: {e}")
            import traceback
            traceback.print_exc()

def main():
    """Main function"""
    # Activate virtual environment
    activate_venv()
    
    # Parse arguments
    parser = argparse.ArgumentParser(description='Calculate FID and IS for 3M dataset')
    parser.add_argument('--base_dir', type=str, default='/home/sanyam/playground/3m-FIDandIS',
                        help='Base directory containing the dataset folders')
    
    args = parser.parse_args()
    
    # Check if base directory exists
    if not os.path.exists(args.base_dir):
        print(f"Error: Base directory {args.base_dir} does not exist")
        return
    
    # Run analysis
    analyzer = FIDISAnalyzer(args.base_dir)
    analyzer.run_analysis()

if __name__ == "__main__":
    main()
